version: 2
jobs:

  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/pligos
    steps:
      - checkout
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: go get -u github.com/stevenmatthewt/semantics
      - run:
          name: cross compile
          command: gox -os="linux darwin windows" -arch="amd64 386" -output="dist/pligos_{{.OS}}_{{.Arch}}"

      - add_ssh_keys
      - run:
          name: create release
          command: |-
            tag=$(semantics --output-tag)
            if [ "$tag" ]; then
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $tag dist/
            else
              echo "The commit message(s) did not indicate a major/minor/patch version."
            fi
